nelmio_api_doc:
    documentation:
        info:
            title: PHR
            description: API endpoints for PHR app. Developed as a part of a bachelor thesis by Vojtěch Voleman.
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
